name: Build and test
on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**.md'
        
concurrency:
  group: ${{ github.head_ref || github.sha }}
  cancel-in-progress: true        

env:
  GITHUB_WORKSPACE: ${{ github.workspace }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_DOTNET_ENABLE_CONCURRENT_EXECUTION: true  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
      - name: Install dotnet-sonarscanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
      - name: Install dotnet cake
        run: |
          dotnet tool install -g Cake.Tool

      - name: Install coverlet
        run: |
          dotnet tool install -g coverlet.console
          
      - name: Cache NuGet Packages
        uses: actions/cache@v3
        with:
          key: nuget-${{ hashFiles('Directory.Packages.props') }}
          path: ~/.nuget/packages
          
      - name: Build the project, run all tests and publish to SonarCloud
        run: |
          dotnet sonarscanner begin \
          /k:"yanpitangui_dotnet-api-boilerplate" \
          /o:"yanpitangui" \
          /d:sonar.login="$SONAR_TOKEN" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.cs.opencover.reportsPaths="./coverage.opencover.xml"
          dotnet cake
          dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
